### ISSUE TITLE
Filter is only partially working

### ISSUE THREAD

**Issue by mimisimon** [nuchi/gmail-inbox-high-contrast-restoration#3]
<img width="1231" alt="Screen Shot 2023-03-21 at 5 00 08 PM" src="https://user-images.githubusercontent.com/128542811/226739795-94976c4b-15e1-4216-9d5b-763c535c0093.png">

**Comment by nuchi** [comment]
Just to double check, does it persist that way after you refresh the page? What browser (and version) are you using, which operating system, are you using any other extensions that might interfere with uBO?

**Comment by mimisimon** [comment]
yes the issue is persisting. Yesterday it was fixed a few seconds after refreshing but it is persisting now. I'm using chrome on mac OSX 10.14.6. I have not installed any new extensions recently but I have attached a screenshot of those that have access to gmail.
<img width="263" alt="Screen Shot 2023-03-21 at 6 11 39 PM" src="https://user-images.githubusercontent.com/128542811/226753904-3da6e13e-84f6-4ad8-8100-fb427d6ddb04.png">

**Comment by nuchi** [comment]
Just loaded up Chrome (I mainly use Firefox) with a dark green image-based theme and can't reproduce your screenshot. Can I request that you try disabling all other extensions besides uBlock Origin and see if the problem persists? Do you have any other custom filter lists or rules in uBlock Origin besides the default ones?

**Comment by mimisimon** [comment]
thanks for your help. It seems that uBlock origin somehow deleted the filter so it is working fine now. I apologize for making you go to such trouble.

**Comment by nuchi** [comment]
I'm glad to hear it's working
