### ISSUE TITLE
Compose button is Still Blue

### ISSUE THREAD

**Issue by sydia1103** [nuchi/gmail-inbox-high-contrast-restoration#4]
This is a great filter list! However, one thing I have noticed is that the compose button is still blue. I believe it was red in the old one. Is this a known issue or is it just me?
![Screen Shot 2023-03-25 at 9 35 08 AM](https://user-images.githubusercontent.com/69560065/227723821-e77873ff-0be4-48ff-9757-5c9f4c240f43.png)

**Comment by nuchi** [comment]
I expect it to be red, so I guess something on your end. Which browser (and version) are you using, which extensions do you have installed?

**Comment by sydia1103** [comment]
I am using Firefox 78. I also tried Chrome 70 and 86, that didn't work either. I only have Ublock Origin installed on Firefox and Chrome. On your end, is the button still red?

**Comment by nuchi** [comment]
Yes:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/16771734/227734629-160d3c2b-81d2-400a-9065-e9a67ab73d68.png">
I suggest trying to update to the latest version of Firefox (v 111) if your operating system is supported and see if the issue persists. (Or latest Chrome, not sure what the latest version number is.) If you can't update, then I'm afraid I don't have any other suggestions.

**Comment by sydia1103** [comment]
Thank you, that did work. Firefox 102.9 ESR was installed and it worked. I am not sure if it works on the latest version of Chrome though.
