### ISSUE TITLE
Email contents font family not respected

### ISSUE THREAD

**Issue by svalentin** [nuchi/gmail-inbox-high-contrast-restoration#5]
When composing an email, or viewing an email, if the user specifies to use a different font family for the email, this filter overrides the displayed font family. For the one using this filter, it appears that changing the font in the email has no effect.

To test, compose an email. Write 2 paragraphs. Set the second paragraph to "Fixed width". The 2 paragraphs should not look the same.

This rule overrides it:
```
mail.google.com##:not(.z0 > .L3, .Bn, .ha > .hP, .gH.acX > .L3.bsQ, .gH.acX > .L3.bsQ *, .amn > .ams, .T-I-atl, .T-I-atl *, .Q0, .Q0 *, .OD, .dt, .v .f1, .v .f1 *, .v .fZ, .v .fZ *, .Wr, .Wr *):style(font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif !important)
```

**Comment by nuchi** [comment]
Many thanks for the detailed report, I'll look into it!

**Comment by svalentin** [comment]
No rush. Thanks for making this filter! I sadly haven't spent the time to offer a solution as well.

**Comment by nuchi** [comment]
Should be fixed in 4976a17

**Comment by svalentin** [comment]
Hmm, interesting. My gmail composer generates a different html. It seems to use `<font>` tag. Example HTML I got from my client:

```
<div id=":14s" class="Am Al editable LW-avf tS-tW tS-tY" hidefocus="true" aria-label="Message Body" g_editable="true" role="textbox" aria-multiline="true" contenteditable="true" tabindex="1" spellcheck="false" style="direction: ltr; min-height: 310px;" aria-owns=":3pm" aria-controls=":3pm">
test1
<div><font face="monospace">test2</font></div>
<div><font face="times new roman, serif">test3</font></div>
</div>
```

But after playing with it for a while, I did see the span with font-family at some point. Not entirely sure when it uses one or the other, but the most common one I've seen is `font`. I think it matters what other settings in the client one has. For example I think that if "plain text mode" is enabled by default, if you change the font it switches to span styling when adding font family, but if you have non-plain mode by default, it uses font tag. (needs more testing though if one cares about this)

I know it's annoying, but do you think we can add `<font>` to the list of tags to ignore? From a brief inspection, I only found the font tag used in some non visible elements. I think it should be safe to add.

Thank you!

**Comment by nuchi** [comment]
Thanks, updated. I also had trouble finding the exact conditions — I think maybe changing existing text gets a `<span>` but selecting a new drop-down option and then starting to type might get a `<font>`. In any case I added an exclusion for `<font>` tags with a `face` attribute.

**Comment by svalentin** [comment]
Thank you for the quick fix, and for the filter as whole!
