### ISSUE TITLE
Search panel font color

### ISSUE THREAD

**Issue by Prynka1995** [nuchi/gmail-inbox-high-contrast-restoration#6]
Hi,

please make the text color in the search bar white, otherwise it is not visible when typing in a dark theme.

Thanks in advance
![image](https://github.com/nuchi/gmail-inbox-high-contrast-restoration/assets/35833727/7c4e4a1e-361b-4f04-8d11-1c8cad0f5c87)

**Comment by nuchi** [comment]
Thanks for the report, I'll take a look. Please confirm which browser and version you're using.

**Comment by Prynka1995** [comment]
Brave 1.47.186 Chromium: 109.0.5414.119  64bit
or
Chrome 108.0.5359.125 64bit

**Comment by nuchi** [comment]
Fixed in https://github.com/nuchi/gmail-inbox-high-contrast-restoration/commit/71e6affde9b9cf415fae5b4c0ce7df06bdab71b6

Thanks again for the report — either I had a typo or maybe the class name changed since I wrote the list. Probably a typo.

**Comment by Prynka1995** [comment]
Thanks a lot!
