### ISSUE TITLE
Settings link is broken

### ISSUE THREAD

**Issue by sn4901** [nuchi/gmail-inbox-high-contrast-restoration#7]
I believe the new Gemini icon might have broken this. The Settings link and Gemini link on the top right doesn't do anything anymore.

Not too big of a deal as I rarely dive into settings so I can just toggle it off, but a heads up. Thanks for this script! I've been enjoying it.

**Comment by nuchi** [comment]
Can't reproduce, works for me. Settings link opens up Quick settings as I expect, Gemini button opens up a tab (saying "Try it out"; I'm not signing up).

Browser, version, operating system, gmail theme?

**Comment by sn4901** [comment]
You're right, my apologies. It was another filter that I had no idea was there that was breaking it. I just noticed it went away with toggling off uBlock Origin and incorrectly attributed it to this one custom filter I use. I'll debug better next time, thank you for looking into it!
